name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: utilities/env.yml
          python-version: 3.9
          activate-environment: goldilocks_cri

      - name: Install extra pip packages
        run: |
          pip install python-picard psychopy

      - name: Run pipeline smoke test
        run: |
          chmod +x run_all.sh
          ./run_all.sh

