name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: utilities/env-ci.yml
          python-version: 3.9
          activate-environment: goldilocks_cri

      - name: Make run_all.sh executable
        run: chmod +x run_all.sh

      
      - name: Run pipeline smoke test(stop on error, with timestamp)
        shell: bash -l {0}
        run: |
          set -e
          echo "Started pipeline at $(date)"
          ./run_all.sh
          echo "Finished pipeline at $(date)"


      - name: Set timestamp for artifact
        id: set_timestamp
        run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

     
     - name: Upload pipeline outputs
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-outputs-${{ steps.set_timestamp.outputs.timestamp }}
          path: |
            figures/output/
            decay/output/
            logistic_gate/output/
            qpt/output/
            synthetic_EEG/output/
            preprocessing/output/
            epochs_features/output/
            statistics/output/
            stimulus_presentation/output/
            local_smoke_test.log
            smoke_test.log
