name: build-and-test

on:
  push:
  pull_request:

jobs:
  figures:
    runs-on: ubuntu-latest
    env:
      MPLBACKEND: Agg   # headless matplotlib
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system packages (LaTeX + tools)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            texlive-latex-extra texlive-pictures texlive-fonts-recommended \
            texlive-science texlive-fonts-extra latexmk \
            poppler-utils imagemagick

      - name: Show tree (top level)
        run: |
          ls -la
          echo "---- figures/ ----"
          ls -la figures || true
          echo "---- utilities/ ----"
          ls -la utilities || true

      - name: Ensure runner can execute the script
        run: chmod +x run_all.sh

      # 👉 NEW: sanitize conda-style paths in requirements before install
      - name: Sanitize Python requirements (strip local conda build paths)
        run: |
          set -euo pipefail
          SRC=""
          OUT=""
          if [ -f requirements.pip.txt ]; then
            echo "Clean requirements.pip.txt already present at repo root; no sanitize needed."
            exit 0
          elif [ -f utilities/requirements.pip.txt ]; then
            echo "Clean utilities/requirements.pip.txt already present; no sanitize needed."
            exit 0
          elif [ -f requirements.txt ]; then
            SRC="requirements.txt"; OUT="requirements.pip.txt"
          elif [ -f utilities/requirements.txt ]; then
            SRC="utilities/requirements.txt"; OUT="utilities/requirements.pip.txt"
          else
            echo "No requirements file found to sanitize."
            exit 0
          fi

          echo "Sanitizing $SRC -> $OUT"
          python - "$SRC" "$OUT" <<'PY'
import re, sys, pathlib
src = pathlib.Path(sys.argv[1])
dst = pathlib.Path(sys.argv[2])

lines = src.read_text().splitlines()
out = []
for raw in lines:
    line = raw.strip()
    if not line or line.startswith("#"):
        out.append(raw)
        continue

    # Drop editable local installs
    if line.startswith("-e ") or line.startswith("--editable"):
        continue

    # Replace direct local file URLs ("pkg @ file:///...") with just the package name
    if "@ file://" in line or line.startswith("file://") or "feedstock_root/build_artifacts" in line:
        m = re.match(r'\s*([A-Za-z0-9_.-]+)\s*@\s*file://.*', line)
        if m:
            out.append(m.group(1))
        # If it's only a file:// URL with no package name, skip it entirely
        continue

    out.append(raw)

dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text("\n".join(out) + "\n")
print(f"Wrote sanitized requirements to {dst}")
PY

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.pip.txt ]; then
            echo "Installing from root requirements.pip.txt"
            pip install -r requirements.pip.txt
          elif [ -f utilities/requirements.pip.txt ]; then
            echo "Installing from utilities/requirements.pip.txt"
            pip install -r utilities/requirements.pip.txt
          elif [ -f requirements.txt ]; then
            echo "Installing from root requirements.txt (unsanitized)"
            pip install -r requirements.txt
          elif [ -f utilities/requirements.txt ]; then
            echo "Installing from utilities/requirements.txt (unsanitized)"
            pip install -r utilities/requirements.txt
          else
            echo "No requirements*.txt found; installing minimal deps"
            pip install numpy matplotlib pyyaml
          fi

      - name: Build figures (incl. TikZ → PDF/PNG)
        run: |
          CRI_FIGS_ONLY=1 ./run_all.sh

      - name: List outputs before smoke test
        run: |
          echo "---- figures/output/ ----"
          ls -la figures/output || true
          echo "---- find figures (2 levels) ----"
          find figures -maxdepth 2 -type f -printf "%p\t%k KB\n" | sort

      - name: Stamp build metadata
        run: |
          python - <<'PY'
          import os, json, platform, sys
          from datetime import datetime, timezone
          from pathlib import Path
          out = Path("figures/output"); out.mkdir(parents=True, exist_ok=True)
          info = {
            "timestamp_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "github": {
              "workflow": os.environ.get("GITHUB_WORKFLOW"),
              "run_id": os.environ.get("GITHUB_RUN_ID"),
              "run_number": os.environ.get("GITHUB_RUN_NUMBER"),
              "sha": os.environ.get("GITHUB_SHA"),
              "ref": os.environ.get("GITHUB_REF"),
              "actor": os.environ.get("GITHUB_ACTOR"),
              "repo": os.environ.get("GITHUB_REPOSITORY"),
            },
            "runtime": {
              "python": sys.version.replace("\n"," "),
              "platform": platform.platform(),
            }
          }
          (out/"build_info.json").write_text(json.dumps(info, indent=2))
          print(json.dumps(info, indent=2))
          PY

      - name: Smoke test figures
        run: |
          python utilities/smoke_test.py --dir figures/output

      - name: Upload figure artifacts
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: |
            figures/output/*.pdf
            figures/output/*.png
            figures/output/manifest.*
            figures/output/build_info.json
