name: Make sample_B.csv

on:
  workflow_dispatch:
    inputs:
      N:
        description: "Number of events to draw"
        default: "2000"
      eta:
        description: "Mixture weight for fast component"
        default: "0.35"
      tau_fast_ms:
        description: "Tau_fast (milliseconds)"
        default: "12"
      tau_slow_s:
        description: "Tau_slow (seconds)"
        default: "120"
      seed:
        description: "RNG seed"
        default: "2025"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure output folder
        run: mkdir -p tierB_tempered/output

      # <<< No NumPy or pandas required — pure stdlib >>>
      - name: Generate tierB_tempered/output/sample_B.csv (stdlib)
        env:
          N: ${{ inputs.N }}
          ETA: ${{ inputs.eta }}
          TAU_FAST_MS: ${{ inputs.tau_fast_ms }}
          TAU_SLOW_S: ${{ inputs.tau_slow_s }}
          SEED: ${{ inputs.seed }}
        run: |
          python - <<'PY'
          import os, csv, random
          N = int(os.getenv("N", "2000"))
          eta = float(os.getenv("ETA", "0.35"))
          tau_fast = float(os.getenv("TAU_FAST_MS", "12")) / 1000.0  # seconds
          tau_slow = float(os.getenv("TAU_SLOW_S", "120"))           # seconds
          seed = int(os.getenv("SEED", "2025"))
          random.seed(seed)

          out_path = "tierB_tempered/output/sample_B.csv"
          kept = 0
          with open(out_path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["t"])
            for _ in range(N):
              # choose component
              lam = (1.0 / tau_fast) if (random.random() < eta) else (1.0 / tau_slow)
              # draw exponential using rate lambda
              t = random.expovariate(lam)
              # administrative right-censor at 600 s (Tier-B window)
              if t <= 600.0:
                w.writerow([f"{t:.9g}"])
                kept += 1
          print(f"Wrote {kept} rows to {out_path}")
          PY

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bot/add-sample-b
          title: "Add sample_B.csv (Tier-B tempered synthetic event times)"
          commit-message: "Add tierB_tempered/output/sample_B.csv (generated via stdlib)"
          add-paths: |
            tierB_tempered/output/sample_B.csv

