name: Run CRI pipeline

on:
  workflow_dispatch:
    inputs:
      figs_only:
        description: "Only build figures (skip long simulations)"
        type: boolean
        default: false
      skip_tex:
        description: "Skip LaTeX/TikZ build (faster; default)"
        type: boolean
        default: true
      auto_install:
        description: "pip install -r requirements.txt"
        type: boolean
        default: true
      skip_diag:
        description: "Skip SI diagnostics (kernel + calibration)"
        type: boolean
        default: false

# allow this workflow to push with GITHUB_TOKEN
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.11 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            utilities/requirements.txt
            **/pyproject.toml

      - name: Install Python deps (sanitized)
        if: ${{ github.event.inputs.auto_install != 'false' }}
        run: |
          python -m pip install --upgrade pip
          if [ -f utilities/requirements.txt ]; then
            # Strip any " @ file://..." local wheel/file pins:
            sed -E 's| @ file://.*$||' utilities/requirements.txt > /tmp/reqs_clean.txt
            # Drop heavy GUI/binary packages that commonly break on CI
            grep -v -E '^(opencv-python(-headless)?|PyQt5|PySide6|vtk|pyvista|pyvistaqt|mne-qt-browser|trame-vtk)$' /tmp/reqs_clean.txt > /tmp/reqs_final.txt
            python -m pip install -r /tmp/reqs_final.txt
          else
            python -m pip install numpy pandas scipy matplotlib PyYAML
          fi

      # Ensure the old tracked CSV doesn't survive this run
      - name: Remove stale tracked decay outputs (pre-run)
        run: |
          git rm -f decay/output/decay_data.csv 2>/dev/null || true
          git rm -f decay/output/decay_curve.csv 2>/dev/null || true
          git rm -f decay/output/fit_decay_results.csv 2>/dev/null || true
          git rm -f decay/output/decay_band.csv 2>/dev/null || true

      - name: Run pipeline
        env:
          CRI_FIGS_ONLY: ${{ github.event.inputs.figs_only }}
          CRI_SKIP_TEX: ${{ github.event.inputs.skip_tex }}
          CRI_AUTO_INSTALL: ${{ github.event.inputs.auto_install }}
          CRI_SKIP_DIAG: ${{ github.event.inputs.skip_diag }}
        run: |
          chmod +x run_all.sh
          ./run_all.sh

      - name: Show regenerated decay_data.csv (debug)
        run: |
          echo "----- HEAD decay/output/decay_data.csv -----"
          sed -n '1,20p' decay/output/decay_data.csv || true
          echo "-------------------------------------------"
          echo "Columns & row count:"
          python - << 'PY'
import pandas as pd
df = pd.read_csv("decay/output/decay_data.csv")
print(df.columns.tolist())
print(f"rows={len(df)}")
PY

      # Commit & push regenerated outputs (even if output/ is gitignored)
      - name: Commit updated decay outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Force-add outputs in case output/ is in .gitignore
          git add -f decay/output/decay_data.csv
          git add -f decay/output/decay_curve.csv
          git add -f decay/output/fit_decay_results.csv
          git add -f decay/output/decay_band.csv

          echo "Git status:"
          git status --porcelain

          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "CI: update decay outputs (3-col CSV) [skip ci]"
            # Push back to the same branch the workflow was run from
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi

      # Artifacts for convenience
      - name: Upload figures
        uses: actions/upload-artifact@v4
        with:
          name: figures-output
          path: figures/output/**

